### ISSUE TITLE
[Suggestion] - Bring back the profiler!

### ISSUE THREAD

**Issue by Jentara** [TorchAPI/Torch#146]
As it was in SESE, http://seserverextender.com/2016/09/22/sese-v1-154-02-828/
The profiler was a great tool for finding issues on a server.

**Comment by XeroCreator** [comment]
I can second this, because SESE had it showing how many ms etc it was using, so we knew what ships /grids were causing the most issues. this would be amazing to see if anyone on server is running crazy scrips without having to police it. 
although right now it's probably gonna just show physics maxed out because of bugs. 
but this is probably already planned tbh.  hopefully...

**Comment by Equinox-** [comment]
v1 d60b165633445d6020c6c25fb950d7a555233713

**Comment by Equinox-** [comment]
Moved to plugin located at https://github.com/TorchAPI/Profiler
