### ISSUE TITLE
[User Story] Better Mods Management

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [TorchAPI/Torch#197]
**As a**
Server Owner

**I want** 
Have the opportunity to watch the list of mods with their names and open their page in the workshop

**So that** 
Be confident in the absence of duplicates and conveniently track their changes by opening the page in the workshop without copying / pasting the identifiers to the mod

![example](https://image.prntscr.com/image/3tbY3K3bTuW9_A5LSww7AA.png)

P.S. English is not my native language and I do not know it well. In advance I apologize for the awkwardness of the translation.

**Comment by zenduin** [comment]
I know this isn't exactly what you wanted but it should help for the time being: https://docs.google.com/spreadsheets/d/1AiIRml3sOcCqSxAKZ0BQjT0S0axILs9-BtC2j-l6-wo/edit?usp=sharing
This is my mod list spreadsheet that I ripped off from Varaxian and modified.
This will give you a list of links to the mods on the workshop and their descriptions.
All you have to edit are the mod workshop IDs in column B, and the ExportToSandbox sheet will give you XML you can paste into your Sandbox.sbc file (don't worry about line breaks since they will be fixed once you save game). Oh and don't forget to put all of that inside your <Mods></Mods> tags.

**Comment by theCalcaholic** [comment]
I would like working on this (since I already figured out most of the required workshop api interaction for my Torch plugin). Just posting to avoid duplicate efforts.
