### ISSUE TITLE
As a Plugin Developer, I want to unload my commands or command module, so that gives me the opportunity to create my plugin features toggles

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Torch#339]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [x] Is this a suggestion?

**Torch Version:** 1.3.1.76-master **SE Version:** 1.192.22

### Expected Behavior
I can unload my plugin commands or command module.

### Observed Behavior
```
public void UnregisterPluginCommands(ITorchPlugin plugin)
{
    // TODO
}
```
![image](https://user-images.githubusercontent.com/1363477/64203005-dc6a1e80-ce92-11e9-9187-5e1c0327c2f4.png)

### Steps to Reproduce
1. Try `UnregisterPluginCommands` method from `CommandManager` class in `Torch.Commands` namespace.

### Other Information
https://github.com/unitycontainer/unity

**Comment by LordTylus** [comment]
Very excellent Idea,

I myself am thinking of moving some commands over to a different plugin
so my idea would be to leave the commands for backwards compatibility in the old plugin

that just says "hey this command was moved over to an other plugin, please install this instead"

so that I can when I detect that plugin just bind the new commands instead.
