### ISSUE TITLE
Automatic restart/update for DS

### ISSUE THREAD

**Issue by Jimmacle** [TorchAPI/Torch#4]
Detect SE/Torch updates and automatically restart the server to apply them.

**Comment by zenduin** [comment]
Adding to this since its going to be part of the same plugin probably.
I want to be able to set a frequency for server restarts, not specific times.
If the server crashes or restarts for any reason it shouldn't auto restart before this amount of time has passed.
Oh and of course it should make sure to save BEFORE the restart, the best I can do now is to schedule a save 1min prior to restart.
Currently with SESE/Essentials you MUST stick to the schedule and if you crash or restart before that you must let it restart. If you toggle off auto restarts before that time and then toggle it back on 10min later or such it just restarts immediately...
